### ISSUE TITLE
New diagnostic repository for team Hyperplane

### ISSUE THREAD

**Issue by babakslt** [nipraxis/diagnostics-template#18]
Hi, this is a request for a new diagnostic repository for our team named "Hyperplane"! :)

**Comment by hveravallaskreppur** [comment]
here's a request for a new repository named one-man-band

**Comment by effigies** [comment]
Both of these exist:

* https://github.com/nipraxis-fall-2022/diagnostics-Hyperplane
* https://github.com/nipraxis-fall-2022/diagnostics-one-man-band
