### ISSUE TITLE
Issue_trial

### ISSUE THREAD

**Issue by manmohidake** [nipraxis/diagnostics-template#27]
New diagnostics repository for team. However, my team members are not around today.

**Comment by matthew-brett** [comment]
What name do you want for your repository?  You can make it today, and they can make their own forks later.

**Comment by manmohidake** [comment]
Perfect, I will make it today in that case. Can I please call the
repository 'CNS_tings'

Best wishes
Mo

**Comment by matthew-brett** [comment]
Your repository should now be available at https://github.com/nipraxis-fall-2022/diagnostics-CNS_tings

**Comment by manmohidake** [comment]
Thank you Matthew!
