### ISSUE TITLE
 Request for a new diagnostics repository for team: Hooray

### ISSUE THREAD

**Issue by RuiLiGitLove** [nipraxis/diagnostics-template#36]

**Comment by RuiLiGitLove** [comment]
@matthew-brett Hello! Sorry this is terribly late, but is it still possible to create a repository for our team now?

**Comment by matthew-brett** [comment]
Yes, sorry - I see that you have seen this - but I have done that now.

https://github.com/nipraxis-fall-2022/diagnostics-Hooray

I have also added the various PRs that will allow you to get started...

**Comment by RuiLiGitLove** [comment]
Thank you Matthew! Sorry it was very late, but we are trying to catch up!
