### ISSUE TITLE
Group76-team-request for a new repo

### ISSUE THREAD

**Issue by alotofeve** [nipraxis/diagnostics-template#40]
Group no 76
name: Group76-repo
Duo Xu duo.xu74@gmail.com; timezone: UTC-7 (main group contact)
Sadoine jeremy.sadoine@inserm.fr; timezone: UTC+1
Kinkini Bhadra bkinkini@gmail.com; timezone: UTC+2
Nastaran Amini nastaranaminii@gmail.com; timezone: UTC-7

**Comment by matthew-brett** [comment]
Your repository should now be available at https://github.com/nipraxis-summer-2023/diagnostics-Group76-repo
