### ISSUE TITLE
new repo for NeuroSpin team

### ISSUE THREAD

**Issue by BUlysse** [nipraxis/diagnostics-template#41]
Hi,

Is is possible to have a new diagnostic repository for our team. Its name is "NeuroSpin"

Thank you

**Comment by matthew-brett** [comment]
Your repository should now be available at https://github.com/nipraxis-summer-2023/diagnostics-NeuroSpin

**Comment by BUlysse** [comment]
Thanks !

**Comment by matthew-brett** [comment]
De rien!
