### ISSUE TITLE
MAS-team

### ISSUE THREAD

**Issue by plachti** [nipraxis/diagnostics-template#48]
Could you please add us as a team with the name "SAM-team"

**Comment by matthew-brett** [comment]
SAM-team or MAS-team?

**Comment by plachti** [comment]
SAM, we changed it

**Comment by plachti** [comment]
SAM-team

**Comment by matthew-brett** [comment]
OK - your repository should now be available at https://github.com/nipraxis-summer-2023/diagnostics-SAM-team
