### ISSUE TITLE
@juliettst

### ISSUE THREAD

**Issue by Shalz650** [nipraxis/diagnostics-template#51]

**Comment by matthew-brett** [comment]
What team name would you like?

**Comment by matthew-brett** [comment]
Assuming this is a previous version of #52 - can I close this one?

**Comment by Shalz650** [comment]
yes

Warm Regards
Shalini

*"A great revolution in just one single individual will help achieve a
change in the destiny of a society and, further, will enable a change in
the destiny of humankind." Daisaku Ikeda*

**Comment by Shalz650** [comment]
Hello @matthew-brett while running the following code in my text editor, 
git add data/group-*/hash_list.txt
ls: data/group-*/hash_list.txt: No such file or directory
(base) MacBook-Pro:data shalinibhattacharya$ ls
group_data.tar

I am getting the above error. Could you please advise?

Thanks 
Shalini
