### ISSUE TITLE
Neurolovers

### ISSUE THREAD

**Issue by Shalz650** [nipraxis/diagnostics-template#52]
Please could you make us i.e. me and my team member @juliettst for a New diagnostic repository?

**Comment by matthew-brett** [comment]
Your repository should now be available at https://github.com/nipraxis-summer-2023/diagnostics-Neurolovers

**Comment by matthew-brett** [comment]
@effies - do you agree?

**Comment by matthew-brett** [comment]
Sorry @effies - my mistake - I meant @effigies

**Comment by matthew-brett** [comment]
Hey @matthew-brett - is correct - is there another way?

Or perhaps @oesteban - do you have any ideas?
