### ISSUE TITLE
Group 18

### ISSUE THREAD

**Issue by FrancescoNottingham** [nipraxis/diagnostics-template#53]

**Comment by FrancescoNottingham** [comment]
Please could you make us a New diagnostic repository?

**Comment by matthew-brett** [comment]
With name "group-18"?  Or some other name?

**Comment by FrancescoNottingham** [comment]
group-18 please

**Comment by matthew-brett** [comment]
Your repository should now be available at https://github.com/nipraxis-summer-2023/diagnostics-group-18

**Comment by FrancescoNottingham** [comment]
Brilliant, thank you!
