### ISSUE TITLE
Requesting the new diagnostics repository for our team..

### ISSUE THREAD

**Issue by Kavithamargabandu** [nipraxis/diagnostics-template#54]
Dear Mathew,
 
 Thank you for this great course, we are learning things, can you make a new diagnostics repository with the team name "NI-Turtles". We are looking forward to learn more from you. These are the participants in our group

1)Kavithamargabandu
2)Prabhakar
3)Anupama
4)ThanushaPrasad
5)Sowmiya
6)Marymartina
7)AnirudhGeorge

**Comment by matthew-brett** [comment]
Your repository should now be available at https://github.com/nipraxis-summer-2023/diagnostics-NI-Turtles

Can I leave you to add your team members, follwing the instructions in session page?

**Comment by Kavithamargabandu** [comment]
Thank you Matt,

   I will add all my team members  :)
